### ISSUE TITLE
Make leading char bigger by faking an overlay

### ISSUE THREAD

**Issue by aethanyc** [abo-abo/ace-window#20]
After reading [Customizing ace-window leading char](http://oremacs.com/2015/02/27/ace-window-leading-char/), I was wondering if `ace-window` could implement a fake overlay to make the leading char bigger and customizable like [switch-window](https://github.com/dimitri/switch-window/blob/master/switch-window.el#L129) did. It's nice since it completely hides the content and line number (if any) to prevent any distraction when choosing the leading char.

On a GUI Emacs, the overlay of `switch-window` looks like:
![switch-window](https://cloud.githubusercontent.com/assets/102858/6463758/1bfe6178-c1f0-11e4-9342-632622b5c412.png)

**Comment by abo-abo** [comment]
It's not that I have a problem re-implementing the functionality of `switch-window`, but I think
that highlighting only a small char is the main advantage of `ace-window` over `switch-window`,
since it doesn't break the flow.

Is there any reason why you want to use `ace-window` over `switch-window`?

**Comment by aethanyc** [comment]
I understand that these UI differences are a matter of design choices. People will get use to it. 

I would prefer `ace-window` over `switch-window` for its abilities to swap and delete buffer. Besides jumping between buffers across frames is very useful when there are many frames on more than one monitor. Thanks for implementing the awesome `ace-window`. :-)
