### ISSUE TITLE
Don't consider invisible text

### ISSUE THREAD

**Issue by Malabarba** [abo-abo/ace-window#33]
1. Invoke `'avi-goto-word-1` in a large org-mode buffer with hidden subtrees, 
2. Hit a common leading char (like `i`)
3. The paths that are offered me are very long (up to 4 characters), because `avy` is taking all the hidden subtrees into consideration.

It would be nice if `avy` checked for the `invisible` text property.

Cheers, and thanks for this great package

**Comment by abo-abo** [comment]
Should work better now, thanks.

**Comment by joedicastro** [comment]
Instead of open a new one, I think that the title could englobe this one too.

The same happen in org-mode with hidden lines.

A pair of screenshots could be helpful,

With hidden text (by outlines):

![2015-05-04-210336_1056x1183_scrot](https://cloud.githubusercontent.com/assets/390964/7460106/12406474-f2a1-11e4-9d05-431ac0393da4.png)

Without hidden text:

![2015-05-04-210500_1056x1183_scrot](https://cloud.githubusercontent.com/assets/390964/7460148/4aafdf10-f2a1-11e4-8308-689e64918aae.png)

**Comment by joedicastro** [comment]
OK, I tested it just right now and works very fine, Thanks for that! :ok_hand: 

But, there is no need to hurry so much, you're a making an excellent work and I hope that you keep doing it a long time, no need to get burned! :smile:

**Comment by abo-abo** [comment]
> But, there is no need to hurry so much, you're a making an excellent work and I hope that you keep doing it a long time, no need to get burned! :smile:

For me it's the opposite: I start to procrastinate when there are too many things to do :smile:

**Comment by Malabarba** [comment]
For me it's the opposite, I tend to procrastinate when there's only one or two things that need doing. Any more than that and I work like a horse. :-)

Anyway, thanks for the quick fix, Oleh!
