### ISSUE TITLE
Confusing names and package separation

### ISSUE THREAD

**Issue by bbatsov** [abo-abo/ace-window#39]
As `ace-window` no longer does what it originally did I think the ace-jump replacement code should be extracted in a separate package and ace-window renamed to something related to the other package. 

As it stands few people will actually understand what the package is all about. If it weren't for our twitter conversation with @Malabarba I wouldn't know about this functionality at all.

**Comment by abo-abo** [comment]
Yes, I should do this at some point.  It's more convenient for me to keep one repository, but two would be better for the users.

**Comment by bbatsov** [comment]
And even in one repo it's kind of confusing to have something named ace-window when it doesn't actually use ace-jump-mode.

**Comment by Malabarba** [comment]
I can agree I too had no idea that ace-window implemented `ace-jump`-like functionality.

If you want to address that, one way is to split `ace-window` into two packages `ace-window` and `package-2`, and then have `ace-window` depend on `package-2`.

If you don't want to split into two, there's another (less conventional) option. You can move `ace-window` entirely to a new package (with a more expressive name), and then have a dummy `ace-window` package that depends on this new package but doesn't do anything else.

**Comment by abo-abo** [comment]
> And even in one repo it's kind of confusing to have something named ace-window when it doesn't actually use ace-jump-mode.

The user-visible behavior is still as if it depended on `ace-jump`. It's just a lot easier on me, since `ace-jump` wasn't designed to be used as a library.

**Comment by abo-abo** [comment]
See the new package at [avy-jump](https://github.com/abo-abo/avy-jump).  After some time, `ace-window` will depend on it.  Please try to test the new package if you can (i.e. try to use it alone without `ace-window` loaded). I'll make the change on MELPA in a few days.

I prefer to keep the name `ace-window`, since there are many links to it. And, from user perspective, it's almost the same as if it depended on `ace-jump-mode` anyway.

**Comment by bbatsov** [comment]
> I prefer to keep the name ace-window, since there are many links to it. And, from user perspective, it's almost the same as if it depended on ace-jump-mode anyway.

You can simply keep a note in the old repo the package was moved somewhere else. I think that's a common practice to avoid this particular problem.

**Comment by bbatsov** [comment]
Btw, what does `avy` stand for? :-)

**Comment by Malabarba** [comment]
>  Please try to test the new package if you can

Using it right now. :+1:

**Comment by abo-abo** [comment]
> Btw, what does avy stand for? :-)

No clue. "a" is for ace, probably.

**Comment by bbatsov** [comment]
Thought it had something to do with your `ivy-mode`. Maybe you just like words ending with `vy`. :-)

**Comment by abo-abo** [comment]
> Maybe you just like words ending with vy. :-)

Yes!

**Comment by Malabarba** [comment]
agile visual yndicators? :-)

**Comment by manuel-uberti** [comment]
This is a very good idea. Hope to see avy-jump in MELPA soon. :-)

**Comment by abo-abo** [comment]
milkypostman/melpa#2750

**Comment by tsdh** [comment]
@abo-abo Ok, cool that avy-jump is now (also) in a separate repo and uses the prefix `avy-` instead of the confusing `avi-` (as discussed in #34).  But how can I now switch to the new one?  Since I use both `ace-window` and wanna use `avy-jump` (the new one), there are two different `avy-jump.el` on `load-path` and which one is active is non-obvious.  And probably in one case my configs for the new `avy-jump.el` won't work whereas in the other case `ace-window` won't work because it requires the old version, no?

**Comment by Malabarba** [comment]
@tsdh If you want to use ace-window too, just wait until it's updated to depend on `avy-jump`.

**Comment by abo-abo** [comment]
@tsdh, avy-jump.el will be removed from ace-window as soon as avy-jump is on MELPA.

**Comment by tsdh** [comment]
Ok, cool.
